version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT:-8080}:8080"
    environment:
      - MODULE_NAME=${MODULE_NAME:-github.com/alimosavifard/zyros-backend}
    env_file:
      - backend/.env
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "${VITE_FRONTEND_PORT:-3000}:3000"
    env_file:
      - frontend/.env

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT:-5432}:5432"

  redis:
    image: redis:6
    ports:
      - "${REDIS_PORT:-6379}:6379"